Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%run ./generate_index.ipynb
generate_index()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mrun[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m./generate_index.ipynb[39m[38;5;124m'[39m)
[0;32m----> 2[0m [43mgenerate_index[49m[43m([49m[43m)[49m

File [0;32m/tmp/ipykernel_2522/1151926238.py:18[0m, in [0;36mgenerate_index[0;34m()[0m
[1;32m     15[0m                 [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mKEYWORDS[39m[38;5;124m'[39m [38;5;129;01min[39;00m line:
[1;32m     16[0m                     keywords [38;5;241m=[39m [x[38;5;241m.[39mstrip() [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m line[38;5;241m.[39mreplace([38;5;124m'[39m[38;5;124m- KEYWORDS:[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m)[38;5;241m.[39mstrip()[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m,[39m[38;5;124m'[39m)]
[0;32m---> 18[0m     index[ipynb] [38;5;241m=[39m [43mkeywords[49m
[1;32m     19[0m     all_keywords [38;5;241m=[39m all_keywords[38;5;241m.[39munion(keywords)
[1;32m     21[0m all_keywords [38;5;241m=[39m [38;5;28msorted[39m([38;5;28mlist[39m(all_keywords))

[0;31mUnboundLocalError[0m: local variable 'keywords' referenced before assignment

